resources:
  - node-app/deployment.yaml
  - node-app/service.yaml
  - mysql/deployment.yaml
  - mysql/service.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - node-app/config.yaml
  - my-app/config.yaml
  - redis/config.yaml
