apiVersion: v1
kind: Service
metadata:
  name: api-health-service
spec:
  selector:
    app: api-health-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300
      name: http
  type: NodePort
