apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-health-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myapp=428346553093.dkr.ecr.eu-north-1.amazonaws.com/my-app
    argocd-image-updater.argoproj.io/myapp.update-strategy: newest-build
    argocd-image-updater.argoproj.io/myapp.allow-tags: regexp:^v[0-9]+\.0\.0$
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ahmed22362/ITI-graduation-project-endpoint-monitor.git
    targetRevision: main
    path: app-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
